# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Td_User_Apli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ap_Nomb', models.CharField(max_length=50)),
                ('Ap_Tiem', models.TimeField()),
                ('Ap_Uso_Bate', models.IntegerField(default=0)),
                ('Ap_Dato_Reci', models.IntegerField(default=0)),
                ('Ap_Dato_Envi', models.IntegerField(default=0)),
                ('Ap_Fech', models.DateField()),
            ],
            options={
                'verbose_name': 'Td_User_Apli',
                'verbose_name_plural': 'Td_User_Aplis',
            },
        ),
        migrations.CreateModel(
            name='Td_User_Cont',
            fields=[
                ('Id_Cont', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Co_Nomb', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Td_User_Cont',
                'verbose_name_plural': 'Td_User_Conts',
            },
        ),
        migrations.CreateModel(
            name='Td_User_Llam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ll_Cont_Nomb', models.CharField(max_length=50, null=True)),
                ('Ll_Cont_Celu', models.CharField(max_length=20)),
                ('Ll_Fech', models.DateField()),
                ('Ll_Tiem_Dura', models.TimeField()),
                ('Ll_Tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Td_User_Llam',
                'verbose_name_plural': 'Td_User_Llams',
            },
        ),
        migrations.CreateModel(
            name='Tm_User',
            fields=[
                ('Id_User', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('No_Celu', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tm_User',
                'verbose_name_plural': 'Tm_Users',
            },
        ),
        migrations.AddField(
            model_name='td_user_llam',
            name='Id_User',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Gentera.Tm_User'),
        ),
        migrations.AddField(
            model_name='td_user_cont',
            name='Id_User',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Gentera.Tm_User'),
        ),
        migrations.AddField(
            model_name='td_user_apli',
            name='Id_User',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='Gentera.Tm_User'),
        ),
    ]
